library(tseries)
#library(TTR)
library(urca)
#library(forecast)
library(RMySQL)
db = dbDriver("MySQL")
con = dbConnect(db, dbname="BTCJPYbitFlyer", user="BTCminer", host="127.0.0.1", password="")
BTC1d = dbGetQuery(con, "select * from 1day where datetime > '2018-04-01 00:00:00' and datetime < '2018-10-25 00:00:00'")
day = as.Date(BTC1d$datetime)
price1d = BTC1d$close
logprice1d = log(price1d)
return1d = diff(logprice1d)*100
#MA1dp5 = SMA(price1d, 5)
#MA1dr5 = SMA(return1d, 5)
#MA1dp25 = SMA(price1d, 25)
#MA1dr25 = SMA(return1d, 25)
#MA1dp3 = SMA(price1d, 3)
#logMA1dp3 = log(MA1dp3)
#returnMA1dp3 = diff(logMA1dp3)*100
par(mfcol=c(2,1))
par(xaxt="n")
plot(day, price1d, type="l", main="Price of BTCJPY", xlab="time", ylab="", lab=c(15,7,0), las=1)
par(xaxt="s")
axis.Date(1, at=seq(min(day),max(day),"months"), format="%m/%d")
#par(new=T)
#plot(MA1dp5, type="l", col=rgb(1,0,0))
#par(new=T)
#plot(MA1dp25, type="l", col=rgb(0,0,1))

par(xaxt="n")
plot(day[2:length(day)], return1d, type="l", main="BTCJPY\'s rate of return", xlab="time", ylab="", lab=c(10,7,6), las=1)
par(xaxt="s")
axis.Date(1, at=seq(min(day),max(day),"months"), format="%m/%d")
#par(new=T)
#plot(MA1dr5, type="l", col=rgb(1,0,0))
#par(new=T)
#plot(MA1dr25, type="l", col=rgb(0,0,1))
#plot(price1d, type="l", main="price1d")
#par(new=T)
#plot(MA1dp3, type="l", col=rgb(1,0,0))
#plot(returnMA1dp3, type="l", main="returnMA1dp3")
#adf.test(MA1dp3[3:143])
#adf.test(returnMA1dp3[3:143])
#par(mfcol=c(1,1))
#acf(returnMA1dp3[3:143], plot=T)
#acf(returnMA1dp3[3:143], plot=T, type="p")

#気を取り直して単位根検定
adf.test(price1d)
adf.test(return1d)

#コレログラム
#png("correlogram_btc1dr.png", width=2560, height=1280)
par(mfcol=c(2,1))
#pdf("BTCJPYcorrelogram.pdf")
acfs = acf(return1d, plot=F)
plot(acfs, main="BTCJPY\'s correlogram")
#plot(acfs, main="BTCJPY\'s correlogram")
#dev.off()
#ARモデル
ar(return1d, aic=T)


system("mv Rplots.pdf analytics1.pdf")
cat("\n")